/**
 * generated by Xtext
 */
package org.xtext.example.browser.validation;

import org.xtext.example.browser.validation.AbstractBrowserValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class BrowserValidator extends AbstractBrowserValidator {
}
