/*
 * generated by Xtext
 */
package org.xtext.example.browser.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.browser.services.BrowserGrammarAccess;

public class BrowserParser extends AbstractContentAssistParser {
	
	@Inject
	private BrowserGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.browser.ui.contentassist.antlr.internal.InternalBrowserParser createParser() {
		org.xtext.example.browser.ui.contentassist.antlr.internal.InternalBrowserParser result = new org.xtext.example.browser.ui.contentassist.antlr.internal.InternalBrowserParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getInstructionsAccess().getAlternatives(), "rule__Instructions__Alternatives");
					put(grammarAccess.getFunctionAccess().getAlternatives(), "rule__Function__Alternatives");
					put(grammarAccess.getGoToAccess().getAlternatives_1(), "rule__GoTo__Alternatives_1");
					put(grammarAccess.getClickOnAccess().getAlternatives_1(), "rule__ClickOn__Alternatives_1");
					put(grammarAccess.getFillAccess().getAlternatives_1(), "rule__Fill__Alternatives_1");
					put(grammarAccess.getSelectAccess().getAlternatives_1(), "rule__Select__Alternatives_1");
					put(grammarAccess.getCheckIfAccess().getAlternatives_1(), "rule__CheckIf__Alternatives_1");
					put(grammarAccess.getCheckIfAccess().getAlternatives_3(), "rule__CheckIf__Alternatives_3");
					put(grammarAccess.getClearAccess().getAlternatives_1(), "rule__Clear__Alternatives_1");
					put(grammarAccess.getBooleanConditionAccess().getAlternatives(), "rule__BooleanCondition__Alternatives");
					put(grammarAccess.getBooleanConditionAccess().getArg1Alternatives_0_0_0(), "rule__BooleanCondition__Arg1Alternatives_0_0_0");
					put(grammarAccess.getBooleanConditionAccess().getArg2Alternatives_0_2_0(), "rule__BooleanCondition__Arg2Alternatives_0_2_0");
					put(grammarAccess.getBooleanConditionAccess().getArg1Alternatives_1_0_0(), "rule__BooleanCondition__Arg1Alternatives_1_0_0");
					put(grammarAccess.getBooleanConditionAccess().getArg2Alternatives_1_2_0(), "rule__BooleanCondition__Arg2Alternatives_1_2_0");
					put(grammarAccess.getBooleanConditionAccess().getArg1Alternatives_4_0_0(), "rule__BooleanCondition__Arg1Alternatives_4_0_0");
					put(grammarAccess.getBooleanConditionAccess().getArg1Alternatives_5_0_0(), "rule__BooleanCondition__Arg1Alternatives_5_0_0");
					put(grammarAccess.getBooleanConditionAccess().getArgAlternatives_6_0_0(), "rule__BooleanCondition__ArgAlternatives_6_0_0");
					put(grammarAccess.getBooleanConditionAccess().getBoolAlternatives_7_2_0(), "rule__BooleanCondition__BoolAlternatives_7_2_0");
					put(grammarAccess.getConditionAccess().getIfCondAlternatives_2_0(), "rule__Condition__IfCondAlternatives_2_0");
					put(grammarAccess.getConditionAccess().getElseifCondsAlternatives_7_2_0(), "rule__Condition__ElseifCondsAlternatives_7_2_0");
					put(grammarAccess.getLoopAccess().getBoolAlternatives_6_0(), "rule__Loop__BoolAlternatives_6_0");
					put(grammarAccess.getWebPageObjAccess().getAlternatives(), "rule__WebPageObj__Alternatives");
					put(grammarAccess.getCollectionsAccess().getAlternatives(), "rule__Collections__Alternatives");
					put(grammarAccess.getFillAllTextFieldsAccess().getAlternatives_2(), "rule__FillAllTextFields__Alternatives_2");
					put(grammarAccess.getWebBrowserAccess().getGroup(), "rule__WebBrowser__Group__0");
					put(grammarAccess.getOngletAccess().getGroup(), "rule__Onglet__Group__0");
					put(grammarAccess.getProcedureLaunchAccess().getGroup(), "rule__ProcedureLaunch__Group__0");
					put(grammarAccess.getGoToAccess().getGroup(), "rule__GoTo__Group__0");
					put(grammarAccess.getClickOnAccess().getGroup(), "rule__ClickOn__Group__0");
					put(grammarAccess.getFillAccess().getGroup(), "rule__Fill__Group__0");
					put(grammarAccess.getSelectAccess().getGroup(), "rule__Select__Group__0");
					put(grammarAccess.getCheckIfAccess().getGroup(), "rule__CheckIf__Group__0");
					put(grammarAccess.getClearAccess().getGroup(), "rule__Clear__Group__0");
					put(grammarAccess.getBooleanConditionAccess().getGroup_0(), "rule__BooleanCondition__Group_0__0");
					put(grammarAccess.getBooleanConditionAccess().getGroup_1(), "rule__BooleanCondition__Group_1__0");
					put(grammarAccess.getBooleanConditionAccess().getGroup_4(), "rule__BooleanCondition__Group_4__0");
					put(grammarAccess.getBooleanConditionAccess().getGroup_5(), "rule__BooleanCondition__Group_5__0");
					put(grammarAccess.getBooleanConditionAccess().getGroup_6(), "rule__BooleanCondition__Group_6__0");
					put(grammarAccess.getBooleanConditionAccess().getGroup_7(), "rule__BooleanCondition__Group_7__0");
					put(grammarAccess.getConditionAccess().getGroup(), "rule__Condition__Group__0");
					put(grammarAccess.getConditionAccess().getGroup_7(), "rule__Condition__Group_7__0");
					put(grammarAccess.getConditionAccess().getGroup_8(), "rule__Condition__Group_8__0");
					put(grammarAccess.getLoopAccess().getGroup(), "rule__Loop__Group__0");
					put(grammarAccess.getTextFieldAccess().getGroup(), "rule__TextField__Group__0");
					put(grammarAccess.getPasswordAccess().getGroup(), "rule__Password__Group__0");
					put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
					put(grammarAccess.getCheckBoxAccess().getGroup(), "rule__CheckBox__Group__0");
					put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
					put(grammarAccess.getLinkAccess().getGroup(), "rule__Link__Group__0");
					put(grammarAccess.getFillAllTextFieldsAccess().getGroup(), "rule__FillAllTextFields__Group__0");
					put(grammarAccess.getVariableAccess().getGroup(), "rule__Variable__Group__0");
					put(grammarAccess.getMemoriseAccess().getGroup(), "rule__Memorise__Group__0");
					put(grammarAccess.getProcedureAccess().getGroup(), "rule__Procedure__Group__0");
					put(grammarAccess.getWebBrowserAccess().getNameAssignment_1(), "rule__WebBrowser__NameAssignment_1");
					put(grammarAccess.getWebBrowserAccess().getOngletsAssignment_3(), "rule__WebBrowser__OngletsAssignment_3");
					put(grammarAccess.getOngletAccess().getUrlAssignment_3(), "rule__Onglet__UrlAssignment_3");
					put(grammarAccess.getOngletAccess().getInsAssignment_4(), "rule__Onglet__InsAssignment_4");
					put(grammarAccess.getInstructionsAccess().getFuncAssignment_0(), "rule__Instructions__FuncAssignment_0");
					put(grammarAccess.getInstructionsAccess().getIfCondAssignment_1(), "rule__Instructions__IfCondAssignment_1");
					put(grammarAccess.getInstructionsAccess().getLoopAssignment_2(), "rule__Instructions__LoopAssignment_2");
					put(grammarAccess.getInstructionsAccess().getCollAssignment_3(), "rule__Instructions__CollAssignment_3");
					put(grammarAccess.getInstructionsAccess().getMemAssignment_4(), "rule__Instructions__MemAssignment_4");
					put(grammarAccess.getInstructionsAccess().getProcsAssignment_5(), "rule__Instructions__ProcsAssignment_5");
					put(grammarAccess.getInstructionsAccess().getLAssignment_6(), "rule__Instructions__LAssignment_6");
					put(grammarAccess.getInstructionsAccess().getVAssignment_7(), "rule__Instructions__VAssignment_7");
					put(grammarAccess.getProcedureLaunchAccess().getProcAssignment_1(), "rule__ProcedureLaunch__ProcAssignment_1");
					put(grammarAccess.getFunctionAccess().getGtlAssignment_0(), "rule__Function__GtlAssignment_0");
					put(grammarAccess.getFunctionAccess().getCobAssignment_1(), "rule__Function__CobAssignment_1");
					put(grammarAccess.getFunctionAccess().getFtfAssignment_2(), "rule__Function__FtfAssignment_2");
					put(grammarAccess.getFunctionAccess().getSelAssignment_3(), "rule__Function__SelAssignment_3");
					put(grammarAccess.getFunctionAccess().getCiAssignment_4(), "rule__Function__CiAssignment_4");
					put(grammarAccess.getFunctionAccess().getClAssignment_5(), "rule__Function__ClAssignment_5");
					put(grammarAccess.getGoToAccess().getLinkAssignment_1_0(), "rule__GoTo__LinkAssignment_1_0");
					put(grammarAccess.getGoToAccess().getVAssignment_1_1(), "rule__GoTo__VAssignment_1_1");
					put(grammarAccess.getClickOnAccess().getButtonAssignment_1_0(), "rule__ClickOn__ButtonAssignment_1_0");
					put(grammarAccess.getClickOnAccess().getLinkAssignment_1_1(), "rule__ClickOn__LinkAssignment_1_1");
					put(grammarAccess.getClickOnAccess().getVAssignment_1_2(), "rule__ClickOn__VAssignment_1_2");
					put(grammarAccess.getFillAccess().getTfAssignment_1_0(), "rule__Fill__TfAssignment_1_0");
					put(grammarAccess.getFillAccess().getPassAssignment_1_1(), "rule__Fill__PassAssignment_1_1");
					put(grammarAccess.getFillAccess().getVAssignment_1_2(), "rule__Fill__VAssignment_1_2");
					put(grammarAccess.getFillAccess().getInputAssignment_3(), "rule__Fill__InputAssignment_3");
					put(grammarAccess.getSelectAccess().getSbAssignment_1_0(), "rule__Select__SbAssignment_1_0");
					put(grammarAccess.getSelectAccess().getVAssignment_1_1(), "rule__Select__VAssignment_1_1");
					put(grammarAccess.getCheckIfAccess().getArgsAssignment_1_0(), "rule__CheckIf__ArgsAssignment_1_0");
					put(grammarAccess.getCheckIfAccess().getV1Assignment_1_1(), "rule__CheckIf__V1Assignment_1_1");
					put(grammarAccess.getCheckIfAccess().getLinKToCheckAssignment_3_0(), "rule__CheckIf__LinKToCheckAssignment_3_0");
					put(grammarAccess.getCheckIfAccess().getV2Assignment_3_1(), "rule__CheckIf__V2Assignment_3_1");
					put(grammarAccess.getClearAccess().getTAssignment_1_0(), "rule__Clear__TAssignment_1_0");
					put(grammarAccess.getClearAccess().getPAssignment_1_1(), "rule__Clear__PAssignment_1_1");
					put(grammarAccess.getClearAccess().getVAssignment_1_2(), "rule__Clear__VAssignment_1_2");
					put(grammarAccess.getBooleanConditionAccess().getArg1Assignment_0_0(), "rule__BooleanCondition__Arg1Assignment_0_0");
					put(grammarAccess.getBooleanConditionAccess().getArg2Assignment_0_2(), "rule__BooleanCondition__Arg2Assignment_0_2");
					put(grammarAccess.getBooleanConditionAccess().getArg1Assignment_1_0(), "rule__BooleanCondition__Arg1Assignment_1_0");
					put(grammarAccess.getBooleanConditionAccess().getArg2Assignment_1_2(), "rule__BooleanCondition__Arg2Assignment_1_2");
					put(grammarAccess.getBooleanConditionAccess().getArg1Assignment_4_0(), "rule__BooleanCondition__Arg1Assignment_4_0");
					put(grammarAccess.getBooleanConditionAccess().getArg1Assignment_5_0(), "rule__BooleanCondition__Arg1Assignment_5_0");
					put(grammarAccess.getBooleanConditionAccess().getArgAssignment_6_0(), "rule__BooleanCondition__ArgAssignment_6_0");
					put(grammarAccess.getBooleanConditionAccess().getBoolAssignment_7_2(), "rule__BooleanCondition__BoolAssignment_7_2");
					put(grammarAccess.getConditionAccess().getIfCondAssignment_2(), "rule__Condition__IfCondAssignment_2");
					put(grammarAccess.getConditionAccess().getFuncAssignment_5(), "rule__Condition__FuncAssignment_5");
					put(grammarAccess.getConditionAccess().getElseifCondsAssignment_7_2(), "rule__Condition__ElseifCondsAssignment_7_2");
					put(grammarAccess.getConditionAccess().getFuncAssignment_7_5(), "rule__Condition__FuncAssignment_7_5");
					put(grammarAccess.getConditionAccess().getFuncAssignment_8_2(), "rule__Condition__FuncAssignment_8_2");
					put(grammarAccess.getLoopAccess().getFuncAssignment_2(), "rule__Loop__FuncAssignment_2");
					put(grammarAccess.getLoopAccess().getBoolAssignment_6(), "rule__Loop__BoolAssignment_6");
					put(grammarAccess.getWebPageObjAccess().getTfAssignment_0(), "rule__WebPageObj__TfAssignment_0");
					put(grammarAccess.getWebPageObjAccess().getPswAssignment_1(), "rule__WebPageObj__PswAssignment_1");
					put(grammarAccess.getWebPageObjAccess().getBtnAssignment_2(), "rule__WebPageObj__BtnAssignment_2");
					put(grammarAccess.getWebPageObjAccess().getCkAssignment_3(), "rule__WebPageObj__CkAssignment_3");
					put(grammarAccess.getWebPageObjAccess().getTAssignment_4(), "rule__WebPageObj__TAssignment_4");
					put(grammarAccess.getWebPageObjAccess().getLAssignment_5(), "rule__WebPageObj__LAssignment_5");
					put(grammarAccess.getTextFieldAccess().getUsernameAssignment_1(), "rule__TextField__UsernameAssignment_1");
					put(grammarAccess.getPasswordAccess().getPasswordAssignment_1(), "rule__Password__PasswordAssignment_1");
					put(grammarAccess.getButtonAccess().getButtonAssignment_1(), "rule__Button__ButtonAssignment_1");
					put(grammarAccess.getCheckBoxAccess().getCheckBoxAssignment_1(), "rule__CheckBox__CheckBoxAssignment_1");
					put(grammarAccess.getTextAccess().getTextAssignment_1(), "rule__Text__TextAssignment_1");
					put(grammarAccess.getLinkAccess().getLinkAssignment_1(), "rule__Link__LinkAssignment_1");
					put(grammarAccess.getCollectionsAccess().getSAssignment_0(), "rule__Collections__SAssignment_0");
					put(grammarAccess.getCollectionsAccess().getCAssignment_1(), "rule__Collections__CAssignment_1");
					put(grammarAccess.getCollectionsAccess().getFAssignment_2(), "rule__Collections__FAssignment_2");
					put(grammarAccess.getCollectionsAccess().getGAssignment_3(), "rule__Collections__GAssignment_3");
					put(grammarAccess.getFillAllTextFieldsAccess().getInputAssignment_2_0(), "rule__FillAllTextFields__InputAssignment_2_0");
					put(grammarAccess.getFillAllTextFieldsAccess().getVAssignment_2_1(), "rule__FillAllTextFields__VAssignment_2_1");
					put(grammarAccess.getVariableAccess().getOAssignment_1(), "rule__Variable__OAssignment_1");
					put(grammarAccess.getVariableAccess().getNameAssignment_2(), "rule__Variable__NameAssignment_2");
					put(grammarAccess.getMemoriseAccess().getObjAssignment_1(), "rule__Memorise__ObjAssignment_1");
					put(grammarAccess.getMemoriseAccess().getVarAssignment_3(), "rule__Memorise__VarAssignment_3");
					put(grammarAccess.getParametersAccess().getParsAssignment(), "rule__Parameters__ParsAssignment");
					put(grammarAccess.getProcedureAccess().getNameAssignment_1(), "rule__Procedure__NameAssignment_1");
					put(grammarAccess.getProcedureAccess().getParamsAssignment_4(), "rule__Procedure__ParamsAssignment_4");
					put(grammarAccess.getProcedureAccess().getInsAssignment_5(), "rule__Procedure__InsAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.browser.ui.contentassist.antlr.internal.InternalBrowserParser typedParser = (org.xtext.example.browser.ui.contentassist.antlr.internal.InternalBrowserParser) parser;
			typedParser.entryRuleWebBrowser();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public BrowserGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(BrowserGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
