/**
 * generated by Xtext
 */
package org.xtext.example.browser.ui.contentassist;

import org.xtext.example.browser.ui.contentassist.AbstractBrowserProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class BrowserProposalProvider extends AbstractBrowserProposalProvider {
}
