/*
 * generated by Xtext
 */
package org.xtext.example.browser;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BrowserStandaloneSetup extends BrowserStandaloneSetupGenerated{

	public static void doSetup() {
		new BrowserStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

