/*
 * generated by Xtext
 */
package org.xtext.example.browser;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BrowserRuntimeModule extends org.xtext.example.browser.AbstractBrowserRuntimeModule {

}
