/*
 * generated by Xtext
 */
package org.xtext.example.browser.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BrowserUiModule extends org.xtext.example.browser.ui.AbstractBrowserUiModule {
	public BrowserUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
